# Generated by scripts/restore-deps.py from scripts/dependencies.json.
# Do not edit by hand; re-run the script instead.
target_include_directories(${COMPILE_ID} PRIVATE ${EXTERN_DIR}/includes)

target_compile_options(${COMPILE_ID} PRIVATE -Wno-extra-qualification)
target_include_directories(${COMPILE_ID} PRIVATE ${EXTERN_DIR}/includes/bs-cordl/include)
target_compile_options(${COMPILE_ID} PRIVATE -DNEED_UNSAFE_CSHARP)
target_compile_options(${COMPILE_ID} PRIVATE -fdeclspec)
target_compile_options(${COMPILE_ID} PRIVATE -DUNITY_2021)
target_compile_options(${COMPILE_ID} PRIVATE -DHAS_CODEGEN)
target_compile_options(${COMPILE_ID} PRIVATE -Wno-invalid-offsetof)
target_compile_options(${COMPILE_ID} PRIVATE -DRAPIDJSON_NEON)
target_compile_options(${COMPILE_ID} PRIVATE -Wno-invalid-offsetof)
target_include_directories(${COMPILE_ID} SYSTEM PRIVATE ${EXTERN_DIR}/includes/fmt/include)
target_compile_options(${COMPILE_ID} PRIVATE -DFMT_HEADER_ONLY)
target_include_directories(${COMPILE_ID} SYSTEM PRIVATE ${EXTERN_DIR}/includes/libil2cpp/libil2cpp)
target_include_directories(${COMPILE_ID} SYSTEM PRIVATE ${EXTERN_DIR}/includes/libil2cpp/external/baselib/Include)
target_include_directories(${COMPILE_ID} SYSTEM PRIVATE ${EXTERN_DIR}/includes/libil2cpp/external/baselib/Platforms/Android/Include)
target_include_directories(${COMPILE_ID} SYSTEM PRIVATE ${EXTERN_DIR}/includes/paper2_scotland2/shared/utfcpp/source)

target_link_directories(${COMPILE_ID} PRIVATE ${EXTERN_DIR}/libs)
RECURSE_FILES(so_list ${EXTERN_DIR}/libs/*.so)
RECURSE_FILES(a_list ${EXTERN_DIR}/libs/*.a)

target_link_libraries(${COMPILE_ID} PRIVATE
	${so_list}
	${a_list}
)
